// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CryptoNotifier.Mac
{
	public partial class SettingsViewController : NSViewController
	{
        AppSettings settings;
        NSUserDefaults defaults;

		public SettingsViewController (IntPtr handle) : base (handle)
		{
            defaults = NSUserDefaults.StandardUserDefaults;
            settings = new AppSettings();
            settings.API_Key = defaults.StringForKey(DefaultKeys.API_KEY) ?? "";
            settings.API_Secret = defaults.StringForKey(DefaultKeys.API_SECRET) ?? "";
            settings.RefreshRate = defaults.FloatForKey(DefaultKeys.REFRESH_RATE);
            settings.Language = defaults.StringForKey(DefaultKeys.LANGUAGE) ?? "";
        }

        partial void OnSaveClicked(NSButton sender)
        {
            var key = APIKeyInput.StringValue;
            var secret = APISecretInput.StringValue;
            var refresh = RefreshRateInput.FloatValue;

            defaults.SetString(key, DefaultKeys.API_KEY);
            defaults.SetString(secret, DefaultKeys.API_SECRET);
            defaults.SetFloat(refresh, DefaultKeys.REFRESH_RATE);
            defaults.SetString("", DefaultKeys.LANGUAGE);
        }

        public override void ViewWillAppear()
        {
            base.ViewWillAppear();
            APIKeyInput.StringValue = settings.API_Key;
            APISecretInput.StringValue = settings.API_Secret;
            RefreshRateInput.StringValue = settings.RefreshRate.ToString();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

        }

        public override void ViewDidDisappear()
        {
            base.ViewDidDisappear();
        }

	}
}
